baseurl = "http://7sharpnine.com/"
title = "7sharp9"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Dave Thomas"
disqusShortname = "7sharp9"
googleAnalytics = "UA-10152365-8"

[Author]
    name = "Dave Thomas"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "7sharp9"
    description = "A blog written by Dave Thomas featuring software development and other musings."
    github = "https://github.com/7sharp9"
    # gitlab = "https://gitlab.com/7sharp9"
    linkedin = "https://linkedin.com/in/dave-thomas-73636221/"
    # gplus = "https://google.com/+XXX"
    twitter = "https://twitter.com/7sharp9_exhumed"
    stackoverflow = "http://stackoverflow.com/users/607275/7sharp9"
    email = "kukulcanenator@gmail.com"
    skype = "7sharpnine"

[Permalinks]
    post = "/:year/:month/:day/:filename/"


[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2
