baseurl = "https://7sharp9.dev/"
title = "7sharp9"
theme = "Vec"
languageCode = "en-us"
copyright = "Dave Thomas"
disqusShortname = "7sharp9"
googleAnalytics = "UA-10152365-8"
enableRobotsTXT = true
paginate = 15

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Dave Thomas"

[Taxonomies]
    tag = "tags"
    series = "series"
    category = "categories"

[Params]
    Description = "A blog by Dave Thomas (7sharp9) featuring programming, running, painting."
    SelfIntro = "A cup of tea would restore my normality. - Douglas Adams"
    githubid = "7sharp9"
    gitlab = "7sharp9"
    LinkedInID = "dave-thomas-73636221"
    twitterid = "7sharp9_"
    stackoverflowid = "http://stackoverflow.com/users/607275/7sharp9"
    Email = "7sharp9@mail.com"
    YouTubeId = "7sharp9b5"
    opengraph = true
    dateFormat = "Mon, Jan 2, 2006"
    author = "7sharp9"
    rss = true
    avatar = "/img/cup_of_tea.jpg"
    keywords = "programming, running, painting, guitar, F#, Rust, Swift, Kotlin, Elixir, TypeScript, C#, dotnet"
    


[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
  name = "About"
  url  = "/about"
  weight = 1
[[menu.main]]
  name = "F#"
  url  = "/FSharp"
  weight = 2
[[menu.main]]
  name = "Running"
  url  = "/Running"
  weight = 3
[[menu.main]]
  name = "Elm"
  url  = "/Elm"
  weight = 4